filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: kuberhealthy
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: jxgh/kh-tls-check
  condition: jxRequirementsTLSCheck.enabled
  name: kh-tls-check
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
